version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    command: npm start
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production